CREATE TABLE IF NOT EXISTS backup (
  id INTEGER PRIMARY KEY,
  date DATETIME NOT NULL,
  status INTEGER NOT NULL DEFAULT 0,
  type INTEGER NOT NULL,
  config_id STRING(255) NOT NULL,
  config_name STRING(255) NULL,
  filename STRING(255) NULL,
  size INTEGER NOT NULL DEFAULT 0
);
